### ISSUE TITLE
Annual MPA reporting meetings

### ISSUE THREAD

**Issue by Kevin-Bancroft** [florianm/mpa-reporting-tasks#10]
Arrange all Annual MPA reporting meetings with all MPC and Asset Leaders:

Meetings scheduled:
EMBMP  8/7/2015 @ 0900
Metro MPs  9/7/2015 @ 0900
JBMP  10/7/2015 @ 0900
SBMPA  10/7/2015  @ 1300
NMPA  13/7/2015  @ 0900
MBIMPA  14/7/2015 @ 0900
RSMP  14/7/2015  @ 1300
WNIMP  21/7/2015  @ 0900
NCMP  22/7/2015  @ 0900
LCSMP   24/7/2015 @ 0900

**Comment by florianm** [comment]
EMBMP  8/7/2015 @ 0900
Metro MPs  9/7/2015 @ 0900
JBMP  10/7/2015 @1300
SBMPA  10/7/2015  @ 1300
NMPA  13/7/2015  @ 0900
MBIMPA  14/7/2015 @ 0900
RSMP  14/7/2015  @ 1300
WNIMP  21/7/2015  @ 0900
NCMP  22/7/2015  @ 0900
LCSMP   24/7/2015 @ 0900

**Comment by Kevin-Bancroft** [comment]
JBMP is at 0900
Kind regards
Kevin Bancroft

Research Scientist (biodiversity patterns)
Marine Science Program, Science Division
Department of Environment and Conservation
email: Kevin.Bancroft@dec.wa.gov.au
ph: +61 (8) 9219 9792  fax: +61 (8) 9334 0327  mob: +61 (4) 2936 0102
*****************************************************************************
________________________________________

**Comment by florianm** [comment]
re-opening and rebranded as having the actual meetings so we can see the times in the waffle.io board!
